from sqlalchemy.orm import Session
from app.database_postgres import Base, engine, get_db
from app.models import Dish

initial_dishes = [
    {"name": "apple_pie", "calories": 296, "protein": 2.4, "fat": 14, "carbs": 41},
    {"name": "baby_back_ribs", "calories": 668, "protein": 36, "fat": 45, "carbs": 10},
    {"name": "baklava", "calories": 306, "protein": 4, "fat": 20, "carbs": 33},
    {"name": "beef_carpaccio", "calories": 181, "protein": 25, "fat": 8, "carbs": 0},
    {"name": "beef_tartare", "calories": 552, "protein": 38, "fat": 45, "carbs": 0},
    {"name": "beet_salad", "calories": 317, "protein": 8, "fat": 5, "carbs": 15},
    {"name": "beignets", "calories": 262, "protein": 4, "fat": 8.5, "carbs": 33},
    {"name": "bibimbap", "calories": 972, "protein": 22, "fat": 22, "carbs": 134},
    {"name": "bread_pudding", "calories": 377, "protein": 6, "fat": 14, "carbs": 55},
    {"name": "breakfast_burrito", "calories": 657, "protein": 25, "fat": 33, "carbs": 60},
    {"name": "bruschetta", "calories": 170, "protein": 5, "fat": 7, "carbs": 20},
    {"name": "caesar_salad", "calories": 470, "protein": 10, "fat": 40, "carbs": 10},
    {"name": "cannoli", "calories": 216, "protein": 5, "fat": 10, "carbs": 25},
    {"name": "caprese_salad", "calories": 300, "protein": 15, "fat": 20, "carbs": 10},
    {"name": "carrot_cake", "calories": 326, "protein": 3, "fat": 16, "carbs": 45},
    {"name": "ceviche", "calories": 200, "protein": 20, "fat": 5, "carbs": 10},
    {"name": "cheesecake", "calories": 401, "protein": 6, "fat": 28, "carbs": 32},
    {"name": "cheese_plate", "calories": 500, "protein": 25, "fat": 40, "carbs": 5},
    {"name": "chicken_curry", "calories": 350, "protein": 30, "fat": 20, "carbs": 15},
    {"name": "chicken_quesadilla", "calories": 529, "protein": 30, "fat": 30, "carbs": 35},
    {"name": "chicken_wings", "calories": 430, "protein": 30, "fat": 30, "carbs": 5},
    {"name": "chocolate_cake", "calories": 352, "protein": 5, "fat": 15, "carbs": 50},
    {"name": "chocolate_mousse", "calories": 355, "protein": 6, "fat": 25, "carbs": 30},
    {"name": "churros", "calories": 116, "protein": 2, "fat": 5, "carbs": 15},
    {"name": "clam_chowder", "calories": 250, "protein": 10, "fat": 15, "carbs": 20},
    {"name": "club_sandwich", "calories": 600, "protein": 25, "fat": 35, "carbs": 45},
    {"name": "crab_cakes", "calories": 300, "protein": 20, "fat": 20, "carbs": 10},
    {"name": "creme_brulee", "calories": 300, "protein": 5, "fat": 25, "carbs": 20},
    {"name": "croque_madame", "calories": 500, "protein": 25, "fat": 30, "carbs": 35},
    {"name": "cup_cakes", "calories": 305, "protein": 3, "fat": 15, "carbs": 40},
    {"name": "deviled_eggs", "calories": 200, "protein": 10, "fat": 15, "carbs": 2},
    {"name": "donuts", "calories": 195, "protein": 2, "fat": 11, "carbs": 22},
    {"name": "dumplings", "calories": 250, "protein": 10, "fat": 10, "carbs": 30},
    {"name": "edamame", "calories": 120, "protein": 11, "fat": 5, "carbs": 10},
    {"name": "eggs_benedict", "calories": 550, "protein": 20, "fat": 35, "carbs": 30},
    {"name": "escargots", "calories": 200, "protein": 15, "fat": 15, "carbs": 5},
    {"name": "falafel", "calories": 333, "protein": 13, "fat": 17, "carbs": 30},
    {"name": "filet_mignon", "calories": 278, "protein": 25, "fat": 20, "carbs": 0},
    {"name": "fish_and_chips", "calories": 800, "protein": 30, "fat": 50, "carbs": 60},
    {"name": "foie_gras", "calories": 400, "protein": 10, "fat": 40, "carbs": 2},
    {"name": "french_fries", "calories": 365, "protein": 4, "fat": 17, "carbs": 48},
    {"name": "french_onion_soup", "calories": 300, "protein": 10, "fat": 15, "carbs": 25},
    {"name": "french_toast", "calories": 450, "protein": 10, "fat": 20, "carbs": 50},
    {"name": "fried_calamari", "calories": 350, "protein": 15, "fat": 20, "carbs": 25},
    {"name": "fried_rice", "calories": 500, "protein": 15, "fat": 20, "carbs": 65},
    {"name": "frozen_yogurt", "calories": 200, "protein": 6, "fat": 4, "carbs": 30},
    {"name": "garlic_bread", "calories": 350, "protein": 7, "fat": 20, "carbs": 35},
    {"name": "gnocchi", "calories": 250, "protein": 7, "fat": 5, "carbs": 45},
    {"name": "greek_salad", "calories": 220, "protein": 6, "fat": 15, "carbs": 10},
    {"name": "grilled_cheese_sandwich", "calories": 400, "protein": 12, "fat": 25, "carbs": 30},
    {"name": "grilled_salmon", "calories": 367, "protein": 34, "fat": 22, "carbs": 0},
    {"name": "guacamole", "calories": 150, "protein": 2, "fat": 13, "carbs": 8},
    {"name": "gyoza", "calories": 200, "protein": 8, "fat": 10, "carbs": 20},
    {"name": "hamburger", "calories": 500, "protein": 25, "fat": 30, "carbs": 40},
    {"name": "hot_and_sour_soup", "calories": 100, "protein": 7, "fat": 3, "carbs": 10},
    {"name": "hot_dog", "calories": 290, "protein": 10, "fat": 20, "carbs": 20},
    {"name": "huevos_rancheros", "calories": 350, "protein": 15, "fat": 20, "carbs": 25},
    {"name": "hummus", "calories": 267, "protein": 12, "fat": 15, "carbs": 20},
    {"name": "ice_cream", "calories": 207, "protein": 4, "fat": 11, "carbs": 24},
    {"name": "lasagna", "calories": 600, "protein": 25, "fat": 30, "carbs": 50},
    {"name": "lobster_bisque", "calories": 250, "protein": 10, "fat": 20, "carbs": 15},
    {"name": "lobster_roll_sandwich", "calories": 450, "protein": 20, "fat": 25, "carbs": 35},
    {"name": "macaroni_and_cheese", "calories": 500, "protein": 15, "fat": 25, "carbs": 50},
    {"name": "macarons", "calories": 250, "protein": 4, "fat": 12, "carbs": 28},
    {"name": "miso_soup", "calories": 84, "protein": 6, "fat": 3, "carbs": 7},
    {"name": "mussels", "calories": 172, "protein": 24, "fat": 4, "carbs": 7},
    {"name": "nachos", "calories": 550, "protein": 15, "fat": 35, "carbs": 45},
    {"name": "omelette", "calories": 154, "protein": 11, "fat": 11, "carbs": 1},
    {"name": "onion_rings", "calories": 411, "protein": 4, "fat": 22, "carbs": 50},
    {"name": "oysters", "calories": 117, "protein": 12, "fat": 3, "carbs": 6},
    {"name": "pad_thai", "calories": 600, "protein": 20, "fat": 20, "carbs": 70},
    {"name": "paella", "calories": 450, "protein": 20, "fat": 15, "carbs": 50},
    {"name": "pancakes", "calories": 350, "protein": 8, "fat": 10, "carbs": 55},
    {"name": "panna_cotta", "calories": 250, "protein": 5, "fat": 20, "carbs": 15},
    {"name": "peking_duck", "calories": 400, "protein": 25, "fat": 30, "carbs": 10},
    {"name": "pho", "calories": 350, "protein": 20, "fat": 10, "carbs": 40},
    {"name": "pizza", "calories": 285, "protein": 12, "fat": 10, "carbs": 36},
    {"name": "pork_chop", "calories": 350, "protein": 30, "fat": 20, "carbs": 0},
    {"name": "poutine", "calories": 740, "protein": 15, "fat": 50, "carbs": 60},
    {"name": "prime_rib", "calories": 400, "protein": 30, "fat": 30, "carbs": 0},
    {"name": "pulled_pork_sandwich", "calories": 500, "protein": 25, "fat": 25, "carbs": 45},
    {"name": "ramen", "calories": 436, "protein": 16, "fat": 17, "carbs": 55},
    {"name": "ravioli", "calories": 300, "protein": 12, "fat": 10, "carbs": 35},
    {"name": "red_velvet_cake", "calories": 400, "protein": 5, "fat": 20, "carbs": 50},
    {"name": "risotto", "calories": 400, "protein": 10, "fat": 15, "carbs": 50},
    {"name": "samosa", "calories": 262, "protein": 6, "fat": 17, "carbs": 22},
    {"name": "sashimi", "calories": 200, "protein": 25, "fat": 5, "carbs": 0},
    {"name": "scallops", "calories": 137, "protein": 23, "fat": 2, "carbs": 5},
    {"name": "seaweed_salad", "calories": 106, "protein": 2, "fat": 7, "carbs": 9},
    {"name": "shrimp_and_grits", "calories": 450, "protein": 20, "fat": 25, "carbs": 35},
    {"name": "spaghetti_bolognese", "calories": 450, "protein": 20, "fat": 15, "carbs": 50},
    {"name": "spaghetti_carbonara", "calories": 574, "protein": 25, "fat": 27, "carbs": 60},
    {"name": "spring_rolls", "calories": 150, "protein": 5, "fat": 5, "carbs": 20},
    {"name": "steak", "calories": 679, "protein": 62, "fat": 48, "carbs": 0},
    {"name": "strawberry_shortcake", "calories": 250, "protein": 4, "fat": 10, "carbs": 35},
    {"name": "sushi", "calories": 200, "protein": 10, "fat": 5, "carbs": 30},
    {"name": "tacos", "calories": 300, "protein": 15, "fat": 15, "carbs": 25},
    {"name": "takoyaki", "calories": 350, "protein": 10, "fat": 20, "carbs": 30},
    {"name": "tiramisu", "calories": 240, "protein": 5, "fat": 15, "carbs": 25},
    {"name": "tuna_tartare", "calories": 200, "protein": 25, "fat": 10, "carbs": 0},
    {"name": "waffles", "calories": 310, "protein": 8, "fat": 15, "carbs": 40},
]

def init_db():
    # Создание данных в таблице dishes, если она пуста
    db: Session = next(get_db())
    try:
        if not db.query(Dish).first():  # Если в таблице нет блюд
            for dish in initial_dishes:
                db.add(Dish(**dish))
            db.commit()
            print("Инициализация завершена: блюда добавлены.")
        else:
            print("Блюда уже существуют в базе данных.")
    except Exception as e:
        print(f"Ошибка при добавлении блюд: {e}")
        db.rollback()